const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer'); // <-- added


const app = express();
const port = 3000;

app.use(cors());
app.use(bodyParser.json());

app.get('/', (req, res) => {
  res.send('Welcome to ReliefLink Backend!');
});

// POST /report - receives report and sends email
app.post('/report', async (req, res) => {
  const report = req.body;
  console.log('Received disaster report:', report);

  // Create transporter
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: 'manasareddymasi123@gmail.com',       // <-- your Gmail address
      pass: 'tvio ulot mvms qndw'          // <-- your Gmail app password
    }
  });

  // Build email content
  const mailOptions = {
    from: 'manasareddymasi123@gmail.com',
    to: 'prernalogachandran@gmail.com',  // <-- email to receive report (can add others separated by commas)
    subject: ' New Disaster Report Submitted',
    text: `
🚨 A new disaster report has been submitted:

• Disaster Type: ${report.type}
• Location: ${report.locationDescription}
• Coordinates: ${report.latitude}, ${report.longitude}
• Severity: ${report.severity}
• Immediate Needs: ${report.needs}
• Reporter Contact: ${report.reporterContact || 'Not Provided'}
      <hr>
      <p><em>This message was automatically generated by ReliefLink Backend</em></p>
    `
  };

  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: 'Report received and email sent successfully!' });
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).json({ error: 'Failed to send email.' });
  }
});

app.listen(port, () => {
  console.log(`Backend server running at http://localhost:${port}`);
});
